# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none
pr:
  - master
  - dev

stages:
  - stage: Check
    jobs:
      - job: Tests
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Python310:
              python.version: '3.10'
        steps:
          - template: .use-python.yml
          - script: cd tests && PYTHONPATH=$(Build.Repository.LocalPath):$PYTHONPATH pytest
            displayName: 'Test'

      - job: Typings
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Python310:
              python.version: '3.10'
        steps:
          - template: .use-python.yml
          - script: mypy lightweight
            displayName: 'Check typings'

      - job: Version
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Python310:
              python.version: '3.10'
        steps:
          - template: .use-python.yml
          - script: cv lightweight --dev
            displayName: 'Check version changed'

      - job: TestCoverage
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Python310:
              python.version: '3.10'
        steps:
          - template: .use-python.yml

          - script: git checkout $(System.PullRequest.SourceBranch)
            displayName: 'Checkout branch'

          - script: cd tests && PYTHONPATH=$(Build.Repository.LocalPath):$PYTHONPATH pytest --cov=lightweight --cov-report=html
            displayName: 'Test with coverage'

          - script: cd tests && coveralls
            displayName: 'Save code coverage'
            env:
              COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
